/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.*;

/**
 *
 * @author culne
 */
public class AnadirNoTripulada extends javax.swing.JFrame {
    
    private Sistema modelo;
    private VentanaPrincipal ventana;
    private String pais;
    private String modeloNave;
    private boolean condicionesOptimas;
    
    /**
     * Creates new form AnadirNoTripulada
     * @param unSistema
     * @param unaVentana
     */
    public AnadirNoTripulada(Sistema unSistema, VentanaPrincipal unaVentana) {
        this.modelo = unSistema;
        this.ventana = unaVentana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radioRusia = new javax.swing.JRadioButton();
        radioEEUU = new javax.swing.JRadioButton();
        radioChina = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioNo = new javax.swing.JRadioButton();
        radioSi = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        labelCampoObligatorio = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir nave no tripulada");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("País");

        radioRusia.setSelected(true);
        radioRusia.setText("Rusia");
        radioRusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRusiaActionPerformed(evt);
            }
        });

        radioEEUU.setText("EEUU");
        radioEEUU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEEUUActionPerformed(evt);
            }
        });

        radioChina.setText("China");
        radioChina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioChinaActionPerformed(evt);
            }
        });

        jLabel3.setText("Óptimas condiciones");

        radioNo.setSelected(true);
        radioNo.setText("No");
        radioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoActionPerformed(evt);
            }
        });

        radioSi.setText("Sí");
        radioSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        labelCampoObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        labelCampoObligatorio.setText("Campo obligatorio");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(radioEEUU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radioChina, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radioRusia)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(radioNo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioSi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCampoObligatorio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(radioRusia)
                .addGap(4, 4, 4)
                .addComponent(radioEEUU)
                .addGap(6, 6, 6)
                .addComponent(radioChina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(radioNo)
                .addGap(2, 2, 2)
                .addComponent(radioSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelCampoObligatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBorrar)
                        .addComponent(btnAnadir))
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        labelCampoObligatorio.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioRusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRusiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRusiaActionPerformed

    private void radioEEUUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEEUUActionPerformed
        pais = "EEUU";
    }//GEN-LAST:event_radioEEUUActionPerformed

    private void radioChinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioChinaActionPerformed
        pais = "China";
    }//GEN-LAST:event_radioChinaActionPerformed

    private void radioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoActionPerformed

    private void radioSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiActionPerformed
        condicionesOptimas = true;
    }//GEN-LAST:event_radioSiActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        resetear();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        if(this.txtModelo.getText().equals("")){
            this.labelCampoObligatorio.setVisible(true);
        }else{

            modeloNave = txtModelo.getText();

            if(radioRusia.isSelected()){
                pais = "Rusia";
            }

            if(radioNo.isSelected()){
                condicionesOptimas = false;
            }

            NoTripulada agregar = new NoTripulada(pais, modeloNave, condicionesOptimas);
            modelo.agregarNave(agregar);
            ventana.actualizar();
            resetear();
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCampoObligatorio;
    private javax.swing.JRadioButton radioChina;
    private javax.swing.JRadioButton radioEEUU;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioRusia;
    private javax.swing.JRadioButton radioSi;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables

    public void resetear(){
        this.txtModelo.setText(null);
        this.radioRusia.setSelected(true);
        this.radioNo.setSelected(true);
        this.labelCampoObligatorio.setVisible(false);
    }
    
}
